# Dialeto para o Hibernate nao se perder
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracao Inteligente de Banco
# Se houver uma URL da Render, ele ignora o H2 e usa o Postgres Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:impactdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# ESSA LINHA É A CHAVE: Ela remove a confusao de drivers
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# Configuracoes Gerais
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
server.port=${PORT:10000}